#!/usr/bin/env python3
"""
Color Calibration Tool

Click on each colored object to sample its HSV values.
The tool will learn the color ranges for your specific objects and lighting.

Usage:
1. Run this script
2. Click on a colored object
3. Type the color name (e.g., 'red', 'blue', 'purple', 'yellow')
4. Repeat for each color you want to detect
5. Press 'S' to save calibration
6. Press 'Q' to quit
"""

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2
import numpy as np
import yaml
import os


class ColorCalibrator(Node):
    def __init__(self):
        super().__init__('color_calibrator')

        self.bridge = CvBridge()
        self.color_image = None
        self.hsv_image = None

        # Collected color samples: {color_name: [list of HSV values]}
        self.color_samples = {}

        # Calibrated ranges: {color_name: {lower: [], upper: [], bgr: []}}
        self.calibrated_colors = {}

        # Click state
        self.click_point = None
        self.sampling_color = None

        # Subscriber
        self.image_sub = self.create_subscription(
            Image, '/camera/camera/color/image_raw', self.image_callback, 10)

        self.get_logger().info('Color Calibrator started')

    def image_callback(self, msg):
        self.color_image = self.bridge.imgmsg_to_cv2(msg, 'bgr8')
        self.hsv_image = cv2.cvtColor(self.color_image, cv2.COLOR_BGR2HSV)

    def sample_color_at_point(self, x, y, region_size=15):
        """Sample HSV values in a region around the click point"""
        if self.hsv_image is None:
            return None

        h, w = self.hsv_image.shape[:2]
        y1 = max(0, y - region_size)
        y2 = min(h, y + region_size)
        x1 = max(0, x - region_size)
        x2 = min(w, x + region_size)

        region = self.hsv_image[y1:y2, x1:x2]

        # Get mean and std of HSV in region
        hsv_mean = np.mean(region, axis=(0, 1))
        hsv_std = np.std(region, axis=(0, 1))

        # Also get the BGR color for visualization
        bgr_region = self.color_image[y1:y2, x1:x2]
        bgr_mean = np.mean(bgr_region, axis=(0, 1))

        return {
            'hsv_mean': hsv_mean,
            'hsv_std': hsv_std,
            'bgr_mean': bgr_mean,
            'region_pixels': region.reshape(-1, 3)
        }

    def add_sample(self, color_name, sample_data):
        """Add a color sample"""
        if color_name not in self.color_samples:
            self.color_samples[color_name] = []

        self.color_samples[color_name].append(sample_data)
        print(f"  Added sample for '{color_name}' - HSV mean: {sample_data['hsv_mean'].astype(int)}")

    def compute_color_ranges(self):
        """Compute HSV ranges from collected samples"""
        self.calibrated_colors = {}

        for color_name, samples in self.color_samples.items():
            if not samples:
                continue

            # Collect all HSV values
            all_hsv = np.vstack([s['region_pixels'] for s in samples])
            all_bgr = np.mean([s['bgr_mean'] for s in samples], axis=0)

            # Compute range with margin
            hsv_min = np.percentile(all_hsv, 5, axis=0)
            hsv_max = np.percentile(all_hsv, 95, axis=0)

            # Add margin for robustness
            margin_h = 10
            margin_s = 30
            margin_v = 30

            lower = np.array([
                max(0, hsv_min[0] - margin_h),
                max(0, hsv_min[1] - margin_s),
                max(0, hsv_min[2] - margin_v)
            ])
            upper = np.array([
                min(180, hsv_max[0] + margin_h),
                min(255, hsv_max[1] + margin_s),
                min(255, hsv_max[2] + margin_v)
            ])

            self.calibrated_colors[color_name] = {
                'lower': lower.astype(int).tolist(),
                'upper': upper.astype(int).tolist(),
                'bgr': all_bgr.astype(int).tolist(),
                'num_samples': len(samples)
            }

            print(f"'{color_name}': lower={lower.astype(int)}, upper={upper.astype(int)}")

    def save_calibration(self, filepath):
        """Save calibrated colors to yaml file"""
        self.compute_color_ranges()

        if not self.calibrated_colors:
            print("No colors calibrated yet!")
            return False

        data = {
            'color_ranges': self.calibrated_colors,
            'calibration_note': 'Generated by calibrate_colors.py'
        }

        with open(filepath, 'w') as f:
            yaml.dump(data, f, default_flow_style=False)

        print(f"\nCalibration saved to: {filepath}")
        return True

    def mouse_callback(self, event, x, y, flags, param):
        if event == cv2.EVENT_LBUTTONDOWN:
            self.click_point = (x, y)


def main():
    rclpy.init()
    node = ColorCalibrator()

    print('\n' + '='*60)
    print('  COLOR CALIBRATION TOOL')
    print('='*60)
    print('\nInstructions:')
    print('1. Click on a colored cube/object')
    print('2. Type the color name and press Enter')
    print('3. Click multiple spots on the same color for better accuracy')
    print('4. Repeat for each color you want to detect')
    print('5. Press S to save calibration')
    print('6. Press Q to quit')
    print('='*60 + '\n')

    cv2.namedWindow('Color Calibration', cv2.WINDOW_NORMAL)
    cv2.setMouseCallback('Color Calibration', node.mouse_callback)

    calibration_path = '/home/robotics_urop/Documents/Robotic AI/Robotic-AI/piper/detection/color_calibration.yaml'

    pending_sample = None

    try:
        while rclpy.ok():
            rclpy.spin_once(node, timeout_sec=0.05)

            if node.color_image is None:
                continue

            vis = node.color_image.copy()
            h, w = vis.shape[:2]

            # Handle click
            if node.click_point is not None:
                x, y = node.click_point
                sample = node.sample_color_at_point(x, y)

                if sample is not None:
                    pending_sample = sample
                    hsv = sample['hsv_mean'].astype(int)
                    print(f"\nClicked at ({x}, {y}) - HSV: H={hsv[0]}, S={hsv[1]}, V={hsv[2]}")
                    print("Type color name (e.g., red, blue, purple, yellow, green): ", end='', flush=True)

                node.click_point = None

            # Draw sampled colors
            y_pos = 30
            cv2.putText(vis, 'Calibrated colors:', (10, y_pos),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)

            for color_name, samples in node.color_samples.items():
                y_pos += 30
                bgr = samples[-1]['bgr_mean'].astype(int)
                cv2.rectangle(vis, (10, y_pos-15), (30, y_pos+5), tuple(map(int, bgr)), -1)
                cv2.putText(vis, f'{color_name} ({len(samples)} samples)', (40, y_pos),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)

            # Instructions
            cv2.putText(vis, 'Click cube | S: Save | Q: Quit', (10, h-10),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.5, (200, 200, 200), 1)

            if pending_sample:
                cv2.putText(vis, 'Type color name in terminal...', (10, h-40),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 255), 2)

            cv2.imshow('Color Calibration', vis)

            key = cv2.waitKey(1) & 0xFF

            if key == ord('s') or key == ord('S'):
                node.save_calibration(calibration_path)

            elif key == ord('q') or key == ord('Q'):
                if node.color_samples:
                    print("\nSave calibration before quitting? (y/n): ", end='', flush=True)
                break

            elif key == 13 or key == 10:  # Enter key
                pass  # Handled by terminal input

    except KeyboardInterrupt:
        pass

    cv2.destroyAllWindows()
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    # Run with terminal input support
    import threading
    import sys

    rclpy.init()
    node = ColorCalibrator()

    calibration_path = '/home/robotics_urop/Documents/Robotic AI/Robotic-AI/piper/detection/color_calibration.yaml'

    print('\n' + '='*60)
    print('  COLOR CALIBRATION TOOL')
    print('='*60)
    print('\nInstructions:')
    print('1. Click on a colored cube/object in the window')
    print('2. Type the color name here and press Enter')
    print('3. Click multiple spots on same color for better accuracy')
    print('4. Press S in the window to save')
    print('5. Press Q in the window to quit')
    print('='*60 + '\n')

    cv2.namedWindow('Color Calibration', cv2.WINDOW_NORMAL)
    cv2.setMouseCallback('Color Calibration', node.mouse_callback)

    pending_sample = None
    running = True

    def input_thread():
        global pending_sample
        while running:
            try:
                color_name = input().strip().lower()
                if color_name and pending_sample is not None:
                    node.add_sample(color_name, pending_sample)
                    pending_sample = None
            except EOFError:
                break

    input_th = threading.Thread(target=input_thread, daemon=True)
    input_th.start()

    try:
        while rclpy.ok() and running:
            rclpy.spin_once(node, timeout_sec=0.05)

            if node.color_image is None:
                continue

            vis = node.color_image.copy()
            h, w = vis.shape[:2]

            # Handle click
            if node.click_point is not None:
                x, y = node.click_point
                sample = node.sample_color_at_point(x, y)

                if sample is not None:
                    pending_sample = sample
                    hsv = sample['hsv_mean'].astype(int)
                    print(f"\nClicked ({x},{y}) - HSV: H={hsv[0]} S={hsv[1]} V={hsv[2]}")
                    print("Enter color name: ", end='', flush=True)

                node.click_point = None

            # Draw sampled colors
            y_pos = 30
            cv2.putText(vis, f'Colors: {len(node.color_samples)}', (10, y_pos),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)

            for color_name, samples in node.color_samples.items():
                y_pos += 30
                bgr = samples[-1]['bgr_mean'].astype(int)
                cv2.rectangle(vis, (10, y_pos-15), (30, y_pos+5), tuple(map(int, bgr)), -1)
                cv2.rectangle(vis, (10, y_pos-15), (30, y_pos+5), (255,255,255), 1)
                cv2.putText(vis, f'{color_name} ({len(samples)})', (40, y_pos),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)

            cv2.putText(vis, 'Click cube | S:Save | Q:Quit', (10, h-10),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.5, (200, 200, 200), 1)

            if pending_sample:
                cv2.putText(vis, '>>> Type color name in terminal <<<', (w//2-150, 30),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 255), 2)

            cv2.imshow('Color Calibration', vis)

            key = cv2.waitKey(1) & 0xFF

            if key == ord('s') or key == ord('S'):
                print("\n--- Saving calibration ---")
                node.save_calibration(calibration_path)

            elif key == ord('q') or key == ord('Q'):
                running = False

    except KeyboardInterrupt:
        pass

    running = False
    cv2.destroyAllWindows()
    node.destroy_node()
    rclpy.shutdown()
